apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deployment-dev
 namespace: cdh-dev
spec:
 selector:
   matchLabels:
    type: web
 replicas: 2
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: cis07385/front:latest
      envFrom:
      - configMapRef:
          name: httpd-cm-dev
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m